### ISSUE TITLE
Not working if deployer is a dependency (in project's vendor folder)

### ISSUE THREAD

**Issue by mmenozzi** [sourcebroker/deployer-extended#1]
If I have deployer as a dependency of my project and I run it with `php vendor/bin/dep db:pull live` these custom recipes are not loaded because `function_exists('\Deployer\set')` in `src/Autoload.php` returns false...

How it's supposed to work in such situation?

**Comment by kszymukowicz** [comment]
We did not tested your case as we will never use Deployer as project dependency because it loads lot of other dependencies. We do not want to pollute dependencies of main project with packages that do only deployment.

But if you have a valid fix for this case I will gladly merge it.

However you case make me thinking that current Autoload.php from composer level is maybe convenient but can bring some problems in future so probably I will remove it in deployer-extended 2.0.

**Comment by mmenozzi** [comment]
I still cannot understand how is it supposed to work.
Now I have deployer installed globally on my machine (version 4.3.0), so it's not a dependency anymore. If I install deployer-extended in my project following the documentation:

```
composer require sourcebroker/deployer-extended
```
And then I execute the `dep` command, I cannot see the deployer-extended tasks.
My `deploy.php` file is:

```php
<?php
namespace Deployer;

require 'recipe/symfony.php';


// Set configurations
set('repository', '***');
set('shared_files', ['app/config/parameters.yml', 'web/.htaccess']);
set('shared_dirs', ['app/logs', 'web/uploads']);
set('writable_dirs', ['app/cache', 'app/logs', 'web/uploads']);
set('writable_use_sudo', false);

// Configure servers
server('production', '***')
    ->user('***')
    ->identityFile()
    ->set('deploy_path', '***')
    ->pty(true);

// Tasks
desc('Restart PHP-FPM service');
task('php-fpm:restart', function () {
    // The user must have rights for restart service
    // /etc/sudoers: username ALL=NOPASSWD:/bin/systemctl restart php-fpm.service
    run('sudo systemctl restart php-fpm.service');
});
//after('deploy:symlink', 'php-fpm:restart');

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');

// Migrate database before symlink new release.
before('deploy:symlink', 'database:migrate');
```

I noticed that in the `autoload` section of composer.json you have defined the `src/Autoload.php` inclusion which, in turns, should trigger the deployer-extended tasks definition. But I cannot understand how the interpreter should include the `vendor/autoload.php` file if I run the global `dep` command (which have its own autoload).

**Comment by kszymukowicz** [comment]
You should have 
`require __DIR__ . '/vendor/autoload.php';`
in your deploy.php.

But I will completely remove the autoload functionality next hours because it cannot work well with deployer installed with composer. 
After that you will need to put something like:
`new \SourceBroker\DeployerExtendeed\Loader();`
in your deploy.php.

At your place I would wait few days as I am extensively refactoring code and creating better documentation together with testing the version with deployer being installed with composer. 

Deployer 5.0 have far less dependency so installing it with composer have much more sense now.

**Comment by mmenozzi** [comment]
Hi,
sorry for my late reply. I already tried  to have 
```php
require __DIR__ . '/vendor/autoload.php'; 
```
in the `deploy.php` but it doesn't work.
Anyway let me know if you already done the refactoring and, if not let me know when it's done.

**Comment by kszymukowicz** [comment]
What functionality you expect to have?

After refactoring database and media synchronization are in separate packages:
https://github.com/sourcebroker/deployer-extended-database
https://github.com/sourcebroker/deployer-extended-media

**Comment by mmenozzi** [comment]
Ok, I need the deployer-extended-database features but as said before it doesn't work.
I added the following to my `deploy.php` file:

```php
require __DIR__ . '/vendor/autoload.php';
new \SourceBroker\DeployerExtendedDatabase\Loader();
```
And the result is:
```
$ dep

Fatal error: Declaration of Symfony\Component\Console\Input\ArrayInput::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /.../vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArrayInput.php on line 190
```
Other info for your reference:
```
$ which dep
/usr/local/bin/dep
$ dep --version
Deployer 4.3.0
```

**Comment by kszymukowicz** [comment]
Seems like you use dep installed globally as phar. Deployer has its own Symfony console and seems like it is not compatibile with the one installed in your project. 

Solution:
1) try to install deployer as composer and run
php ./vendor/bin/dep

2) if you still want to use deployer as phar then try to run not "dep" but some real command like "dep list". I had case like you also and the problem was only when I was running "dep" alone without any arguments.

**Comment by mmenozzi** [comment]
Yes I'm using deployer installed globally because it seems supported looking at the docs.
I tried the solution 2 and it works but is very ugly...

**Comment by kszymukowicz** [comment]
I just added the note to documentation about your case.

For now I would advice you to use deployer as composer package. Its the way I use it now for all new projects and for sure its far better tested that phar mode.

I am not sure if you know the trick how to use "dep" command alone without having to use "./vendor/bin/dep". You can put:

export PATH="$PATH:./vendor/bin"

to you ~/.profile or ~/.bashrc

**Comment by mmenozzi** [comment]
I don't like to use deployer as a project dependency because I see it as a deployment tool not related with project itself. For example, in legacy projects which requires PHP 5.5 I cannot use deployer 4 because it requires PHP >= 5.6. In such situation I'm able to use deployer as global phar.

Thank you anyway!
